UPDATE public.teams SET flag_emoji = CASE code
  WHEN 'ALG' THEN '🇩🇿'
  WHEN 'ARG' THEN '🇦🇷'
  WHEN 'AUS' THEN '🇦🇺'
  WHEN 'AUT' THEN '🇦🇹'
  WHEN 'BEL' THEN '🇧🇪'
  WHEN 'BIH' THEN '🇧🇦'
  WHEN 'BRA' THEN '🇧🇷'
  WHEN 'CAN' THEN '🇨🇦'
  WHEN 'CIV' THEN '🇨🇮'
  WHEN 'COD' THEN '🇨🇩'
  WHEN 'COL' THEN '🇨🇴'
  WHEN 'CPV' THEN '🇨🇻'
  WHEN 'CRO' THEN '🇭🇷'
  WHEN 'CUW' THEN '🇨🇼'
  WHEN 'CZE' THEN '🇨🇿'
  WHEN 'ECU' THEN '🇪🇨'
  WHEN 'EGY' THEN '🇪🇬'
  WHEN 'ESP' THEN '🇪🇸'
  WHEN 'FRA' THEN '🇫🇷'
  WHEN 'GER' THEN '🇩🇪'
  WHEN 'GHA' THEN '🇬🇭'
  WHEN 'HAI' THEN '🇭🇹'
  WHEN 'IRN' THEN '🇮🇷'
  WHEN 'IRQ' THEN '🇮🇶'
  WHEN 'JOR' THEN '🇯🇴'
  WHEN 'JPN' THEN '🇯🇵'
  WHEN 'KOR' THEN '🇰🇷'
  WHEN 'KSA' THEN '🇸🇦'
  WHEN 'MAR' THEN '🇲🇦'
  WHEN 'MEX' THEN '🇲🇽'
  WHEN 'NED' THEN '🇳🇱'
  WHEN 'NOR' THEN '🇳🇴'
  WHEN 'NZL' THEN '🇳🇿'
  WHEN 'PAN' THEN '🇵🇦'
  WHEN 'PAR' THEN '🇵🇾'
  WHEN 'POR' THEN '🇵🇹'
  WHEN 'QAT' THEN '🇶🇦'
  WHEN 'RSA' THEN '🇿🇦'
  WHEN 'SEN' THEN '🇸🇳'
  WHEN 'SUI' THEN '🇨🇭'
  WHEN 'SWE' THEN '🇸🇪'
  WHEN 'TUN' THEN '🇹🇳'
  WHEN 'TUR' THEN '🇹🇷'
  WHEN 'URY' THEN '🇺🇾'
  WHEN 'USA' THEN '🇺🇸'
  WHEN 'UZB' THEN '🇺🇿'
  WHEN 'ENG' THEN '🏴󠁧󠁢󠁥󠁮󠁧󠁿'
  WHEN 'SCO' THEN '🏴󠁧󠁢󠁳󠁣󠁴󠁿'
  ELSE flag_emoji
END;